### PR TITLE
Mile-stone 7 : Using Bootstrap

### PR DESCRIPTION
**Pull request by enaburekhan**
**Newsweek clone by Tahiry RANDRIAMIARINTSOA and Eric Enaburekhan.**
**In this project:**

- Use the twitter-bootstrap framework for HTML layout and responsiveness
- Use twitter-bootstrap flex and grid properties.
- Use CSS 3 properties

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team!! Great job working on the project!!

There are still some issues to be addressed.

## Required Changes
### [Mandatory] :red_circle: 

- [ ] Issue link in the README file takes to an unrelated project issues page.

- [ ] Fix horizontal scrolling.

- [ ] Custom stylesheet should be after Bootstrap's CDN link, this helps and makes it easier to override and customize Bootstrap classes. Is a "best practice".

- [ ] The menu is part of the Navbar in the original website. Please fix this.

- [ ] Navbar does not match the original in desktop version
image

- [ ] The Newsweek logo should be an image. We could inspect the website to retrieve the actual logo image link to use in the project.
image

- [ ] Missing Border top and Border bottom
image

- [ ] Remove the borders to match original style.
image

- [ ] Editor's pick elements not aligned

- [ ] Editor's pick has a border. We should match the original style.
image

- [ ] Image from Newsletter is distorted.
image

- [ ] Footer Newsweek should be an image.
image

- [ ] Website looses proportions on larger screens. We should use the browsers **media query inspector** to see if the project displays as intended in different screen sizes.

- [ ] Navbar overlaps section titles in tablet and mobile version (768)
image

- [ ] Element overlaps other elements when scrolling. This may be caused by a sticky top CSS property.
image

- [ ] Navbar does not match original in tablet version (768)
image

- [ ] Red tag overlaps title in tablet version
image

- [ ] Articles are not aligned correctly in tablet version
image

- [ ] Newsletter does not match original in table mode
https://microverse.zoom.us/j/3463620405?pwd=bnJCQnl1eXBuVVRQSUpQL2dRYUdwdz09

- [ ] More Stories goes below Opinion section
image

- [ ] Navbar hides after vertical scrolling
image

- [ ] should have a margin left as original in mobile version
image

- [ ] Section should matching style on mobile version
image

- [ ] Social icons should match original in footer mobile version
image

### [OPTIONAL]  :large_blue_circle: 

- [ ] The readme should have relevant information, if there is no License is better to omit and leave out this part.
image

- [ ] ```<head>```, ```<main>```, and ```<footer>``` should the most outer tags inside the ```<body>```, It would be better not to wrap them inside a ```<div>``` container and find another way to have the same result.

- [ ] Maintain the same format through the whole file. Erase the extra white space. 

### [Comments] :green_circle: 

- If you're using a template for your projects ensure is a blank template, that gives no clue to unrelated projects, because it could be misleading for the reader and create confusion.
image

- Is preferred to create your own template based on someone else's rather than reusing. Take into consideration that the project used as a template is from a non-related HTML and CSS project. This could create unexpected bugs and linter issues.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great effort working on the previously required changes!

There are still some issues to be addressed.

## Required Changes
### [Mandatory] :red_circle: 

- [ ] The website still presents a horizontal scrolling.

- [ ] Remove borders.There were some improvements but there are still some issues related. See previous review. 
image

- [ ] Navbar doesn't; match mobile version.

- [ ] Navbar overlaps section titles
image

- [ ] Subscribe section magazine is outside container.
image


### [OPTIONAL]  :large_blue_circle: 

- [ ] We should use the media query inspector and see if the website looks as intended in larger screens.
image
### [Comments] :green_circle: 

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by enaburekhan** [comment]
**Code review comments effected.**

- Fix horizontal scroll
- Remove border
- Fix subscribe section
- Re-align the navbar on the mobile section

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. I also commend your effort in fixing the issues raised by the previous reviewer. However, there are some changes that are still required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]** :red_circle: 

_In this project, you are asked to be more precise and to make sure that your page looks exactly the same as the source page. As a result, we have to make sure that the goal is achieved, using Bootstrap._

- [ ] Your page still presents a horizontal scroll bar.
- I dug deep into this and I found out that the horizontal scroll bar was as a result of a bootstrap class rule (row) you applied on the __first `<div>` child in your `<main>` tag__. Please use your developer tools to confirm this and fix it.

- [ ] You are still having some padding issues on your page. 
- You have some padding rules affecting the title and description section of each of the articles. Kindly ensure that all the contents of each article occupy exactly the same space horizontally and vertically. Check the image below for more details.

Source page:


Your page:


- This is also the case in almost all other sections in your project. Kindly fix the padding so it looks like the original. For instance, see images below `Editor's pick` section

Source Page:
`Editor's Pick` section


Your page:


**On large screen size**
- [ ] In more stories section, there's too much space between the story's image and the title section. 

Source page:


Your page:


- [ ] This excess space is also seen in the opinions section.

Source page:


Your page:



**[ COMMENTS ]** :writing_hand: 

- Most of the issues raised above are applicable to more than one section in your project. Kindly fix the ones pointed out, check for other instances where such is happening, and fix them as appropriate.
- Again, the browser's developer tools is a good tool when trying to solve problems like this. Kindly use it to narrow down which rule is causing these paddings to fix them as appropriate.

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

**Comment by enaburekhan** [comment]
**Code review changes effected**.

- Fix horizontal scroll
- Fix padding and border issue 
- Fix excess space

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

## Hello team,

**Great job implementing the changes. However, there are still some more changes required.**

## Mandatory

1). **There is too much spacing on the left and right side of the full-size screen page when compared to the original page. Hint: You could try using `container-fluid` class instead of `container-xl` class.**

### 2). Screen size: 767px

-  **There is a lot of spacing between the images and the side text, for all the sections, more stories, opinion, world, sports etc.**

-  **The large images do not cover the full width of the page as it is on the original page. Please fix that. Below is a screenshot example.**

original | clone
---------| -------
newsweek_original | newsweek_clone

**Happy coding 😃.**

**PS: You can reach me on slack(Rose Wanjohi).**

**Comment by enaburekhan** [comment]
**Code review changes effected.**

- Resize fullscreen
- Fix image size at 767px

**Review by arslanbisharat — APPROVED** [review]
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

**Pull request merged**
